version: '3.4'

services:
  twin-api:
    build:
      context: .
      dockerfile: src/Tributech.DataSpace.Twin-API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5120:80"
    networks:
      - data-net

networks:
  data-net:
