version: '3.4'

services:
  neo4j:
    image: neo4j:4.2.3
    restart: always
    environment:
      - NEO4J_dbms.security.procedures.allowlist=apoc.*,algo.*
      - NEO4J_AUTH=neo4j/password
      - NEO4JLABS_PLUGINS=["apoc"]
    networks:
      - data-net
    volumes:
      - neo4j:/data
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  data-net:
volumes:
  neo4j: